-- require("tobybot11.plugins-setup")
require("packer-config")

require("tobybot11.core.options")
require("tobybot11.core.colorscheme")
require("tobybot11.core.keymaps")

require("tobybot11.plugins.autopairs")
-- require("plugins.autopairs")
require("tobybot11.plugins.comment")
require("tobybot11.plugins.gitsigns")
require("tobybot11.plugins.hlargs")
require("tobybot11.plugins.impatient")
require("tobybot11.plugins.nvim-cmp")
require("tobybot11.plugins.nvim-tree")
require("tobybot11.plugins.lualine")
require("tobybot11.plugins.rust-tools")
require("tobybot11.plugins.symbols-outline")
require("tobybot11.plugins.telescope")
require("tobybot11.plugins.treesitter")
require("tobybot11.plugins.vimspector")

require("tobybot11.plugins.lsp.mason")
require("tobybot11.plugins.lsp.lspsaga")
require("tobybot11.plugins.lsp.lspconfig")
require("tobybot11.plugins.lsp.null-ls")
